refactor : ci 수정

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -13,12 +13,16 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Make application.properties
+      - name: Ensure resources directory exists
+        run: mkdir -p src/main/resources
+
+      - name: Decode and create application.properties
         run: |
-          cd ./src/main/resources
-          echo "${{ secrets.APPLICATION_PROPERTIES }}" | base64 --decode > ./application.properties
+          echo "${{ secrets.APPLICATION_PROPERTIES }}" | base64 --decode > src/main/resources/application.properties
         shell: bash
 
+      - name: Check application.properties
+        run: cat src/main/resources/application.properties || echo "File not found"
 
       - name: Grant execute permission for Gradle
         run: chmod +x ./gradlew
